<?php
use Migrations\AbstractSeed;

/**
 * Users seed.
 */
class UsersSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'username' => 'mobrazil@icloud.com',
                'password' => '$2y$10$r4PHDOVlTmcPPGYBFiFF/.Y0oFBjz1Hy0XyGfkYpk0aOgkD7l.Y9u',
                'fullname' => 'Miquel Brazil',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Atlanta',
                'state' => 'GA',
                'created' => '2016-11-24 12:57:54',
                'updated' => '2016-11-24 12:57:54',
            ],
            [
                'id' => '2',
                'username' => 'jessica.reinhart@aidshealth.org',
                'password' => '$2y$10$lI5.qKEx2uEKPJasL/9Rj.VGQD/dGJAolmzHxBTqNsplNq6qbAMRm',
                'fullname' => 'Jessica Reinhart',
                'role' => 'mobilizer',
                'region_id' => '3',
                'city' => 'Brooklyn',
                'state' => 'NY',
                'created' => '2017-01-10 15:36:57',
                'updated' => '2017-02-28 16:45:59',
            ],
            [
                'id' => '3',
                'username' => 'tyler@sobeviral.com',
                'password' => '$2y$10$/xLmWZ/5Jcu.wRLEd6qQheAhbau/fm.m0MbvYnI3Vcva0adLHw38.',
                'fullname' => 'Tyler Narducci',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => NULL,
                'state' => 'FL',
                'created' => '2017-01-10 15:40:49',
                'updated' => '2017-02-28 16:45:22',
            ],
            [
                'id' => '4',
                'username' => 'jason.king@aidshealth.org',
                'password' => '$2y$10$vyJZaMcQqjIwtDUbeEbJMODwTk18fl.6JAomT.B8B8EMV8McTWTpi',
                'fullname' => 'Jason King',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => NULL,
                'state' => 'FL',
                'created' => '2017-01-10 16:08:54',
                'updated' => '2017-02-28 16:43:59',
            ],
            [
                'id' => '6',
                'username' => 'mbrazil@clevelandtaskforce.org',
                'password' => '$2y$10$2vTCWyTeMjIThcV2lh8rtuLa90wbyWR9p47b3HEGC/Qb90nYQwYaC',
                'fullname' => 'Miquel Brazil',
                'role' => 'admin',
                'region_id' => '1',
                'city' => 'Cleveland',
                'state' => 'OH',
                'created' => '2017-02-28 11:59:12',
                'updated' => '2017-02-28 11:59:12',
            ],
            [
                'id' => '7',
                'username' => 'dbarnett@clevelandtaskforce.org',
                'password' => '$2y$10$jx3/LaDgU8f6SU3Exd.UN.XSUetPiMay6tTEr/AcJ0Iq7wtwFCaSG',
                'fullname' => 'Derek Barnett',
                'role' => 'mobilizer',
                'region_id' => '1',
                'city' => 'Cleveland',
                'state' => 'OH',
                'created' => '2017-02-28 16:47:32',
                'updated' => '2017-02-28 16:47:32',
            ],
            [
                'id' => '8',
                'username' => 'timothy.webb@aidshealth.org',
                'password' => '$2y$10$BdSqCH9W7aqoOY00SirEYu2Rrme3.L73.Zlsa8FNiCgKiO3ax3hL.',
                'fullname' => 'Timothy Webb',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Atlanta',
                'state' => 'GA',
                'created' => '2017-02-28 16:49:03',
                'updated' => '2017-02-28 16:49:03',
            ],
            [
                'id' => '9',
                'username' => 'sharon.brown@aidshealth.org',
                'password' => '$2y$10$GftRyrNrvUd6i5bifMDNmufE7VAPfcahcZILadtXfFDj65VMDnPHS',
                'fullname' => 'Sharon Brown',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Clinton',
                'state' => 'MS',
                'created' => '2017-02-28 16:49:25',
                'updated' => '2017-02-28 16:50:38',
            ],
            [
                'id' => '10',
                'username' => 'sashika.baunchand@aidshealth.org',
                'password' => '$2y$10$MPf7q769OuhIvtYiS/4lje7W2BSjPFJpNdpgjqrb2ldO..HYVdsyS',
                'fullname' => 'Sashika Baunchand',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Baton Rouge',
                'state' => 'LA',
                'created' => '2017-02-28 16:51:02',
                'updated' => '2017-02-28 16:51:02',
            ],
            [
                'id' => '11',
                'username' => 'terl.gleason@aidshealth.org',
                'password' => '$2y$10$XR5EvTCrJpw7kLsalkEhaeVa1C9XmDzbIUFsRo8XOlai54A/sVzyW',
                'fullname' => 'Terl Gleason',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Greensboro',
                'state' => 'NC',
                'created' => '2017-02-28 16:51:57',
                'updated' => '2017-02-28 16:51:57',
            ],
            [
                'id' => '12',
                'username' => 'wandabrendle.moss@aidshealth.org',
                'password' => '$2y$10$OUI07pI7W1SiKkcCJ5iJxOZ0Byb2/N.rP04usSOhso0iMfdLrAfei',
                'fullname' => 'Wanda Brendle-Moss',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Winston-Salem',
                'state' => 'NC',
                'created' => '2017-02-28 16:53:04',
                'updated' => '2017-02-28 16:53:04',
            ],
            [
                'id' => '13',
                'username' => 'rebecca.strong@aidshealth.org',
                'password' => '$2y$10$tDzkgXKdh1Ggv6Y4w2rKwOoo1LclCkJ7QcBI.kkPruu06MAI/.mUO',
                'fullname' => 'Rebecca Strong',
                'role' => 'mobilizer',
                'region_id' => '1',
                'city' => 'Cleveland',
                'state' => 'OH',
                'created' => '2017-02-28 16:58:33',
                'updated' => '2017-02-28 16:58:33',
            ],
            [
                'id' => '14',
                'username' => 'tracy.jones@aidshealth.org',
                'password' => '$2y$10$NkCYPhpE8yHlNN9x216EeeApWjhtZO8EqM.KFj.byS0kQOlk6RfqG',
                'fullname' => 'Tracy Jones',
                'role' => 'mobilizer',
                'region_id' => '1',
                'city' => 'Cleveland',
                'state' => 'OH',
                'created' => '2017-02-28 16:58:53',
                'updated' => '2017-02-28 16:58:53',
            ],
            [
                'id' => '15',
                'username' => 'valerie.brown@aidshealth.org',
                'password' => '$2y$10$qiml.0cCt4HLM5O6qwtX8OTS9IsWj.M9zsuT6FvqmuwstBb2cfZBG',
                'fullname' => 'Valerie Brown',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Clinton',
                'state' => 'MS',
                'created' => '2017-03-07 16:18:10',
                'updated' => '2017-03-07 16:18:10',
            ],
            [
                'id' => '16',
                'username' => 'jeffrey.owens@aidshealth.org',
                'password' => '$2y$10$IL9rwe89DgZeg.OvphLCGONILnKCnvqVN/Paa9Lbd2Hivj8E5a.g.',
                'fullname' => 'Jeffrey Owens',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => NULL,
                'state' => 'FL',
                'created' => '2017-03-07 16:19:00',
                'updated' => '2017-03-07 16:19:00',
            ],
            [
                'id' => '17',
                'username' => 'guttenberg.pierre@aidshealth.org',
                'password' => '$2y$10$1H5CXLLRPYQ2YOhDcXjuWu1QQh3TQwYCaLvXBcZRplFd4rmCtPrAy',
                'fullname' => 'Pierre Guttenberg',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Tampa',
                'state' => 'Fl',
                'created' => '2017-03-07 16:19:35',
                'updated' => '2017-03-07 16:19:35',
            ],
            [
                'id' => '18',
                'username' => 'john.reed@aidshealth.org',
                'password' => '$2y$10$p7KBT1.tCeE0Y.prVuNKmujCPyFPv.8qZKJAkVenj1p9xNDg.3SEW',
                'fullname' => 'John Reed',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Forth Worth',
                'state' => 'TX',
                'created' => '2017-03-07 16:46:48',
                'updated' => '2017-03-07 16:46:48',
            ],
            [
                'id' => '19',
                'username' => 'edward.jones@aidshealth.org',
                'password' => '$2y$10$P5LVkpfN2ur.lr9GyRSeOeKRiwECMd6n/BtUK0uJHD3BDWoeM6oTy',
                'fullname' => 'Edward Jones',
                'role' => 'mobilizer',
                'region_id' => '2',
                'city' => 'Dallas',
                'state' => 'TX',
                'created' => '2017-03-07 16:47:10',
                'updated' => '2017-03-07 16:47:10',
            ],
            [
                'id' => '20',
                'username' => 'jesse.brooks@aidshealth.org',
                'password' => '$2y$10$2VVU9wWIujTe6n/QhVhTF.MFL58oiOhZx3NvzlwpkfIfhDEQcMFWO',
                'fullname' => 'Jesse Brooks',
                'role' => 'mobilizer',
                'region_id' => '5',
                'city' => 'Oakland',
                'state' => 'CA',
                'created' => '2017-03-07 16:47:34',
                'updated' => '2017-03-07 16:47:34',
            ],
            [
                'id' => '21',
                'username' => 'david.robertson@aidshealth.org',
                'password' => '$2y$10$T75gSGFxzFjBFxg4w1nbi.JD/UM1NIrOpT06OlAAnpwPPiTkpg.U2',
                'fullname' => 'David Robertson',
                'role' => 'mobilizer',
                'region_id' => '1',
                'city' => 'Chicago',
                'state' => 'IL',
                'created' => '2017-03-07 16:55:36',
                'updated' => '2017-03-07 16:55:36',
            ],
            [
                'id' => '22',
                'username' => 'guy.anthony@aidshealth.org',
                'password' => '$2y$10$24YoHAzGCMXYe.Ed0q76kOkyzXautF3tDJGk7WTQYz11jDrGBXcmq',
                'fullname' => 'Guy Anthony',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Washington',
                'state' => 'DC',
                'created' => '2017-03-07 16:56:22',
                'updated' => '2017-03-07 16:56:22',
            ],
            [
                'id' => '23',
                'username' => 'miranda.martinez@aidshealth.org',
                'password' => '$2y$10$1i73zUqi438lC/MmlRy9RuLJOZ5.suF3lU.Oy1wW6s9CqfpCsqo86',
                'fullname' => 'Miranda Martinez',
                'role' => 'mobilizer',
                'region_id' => '5',
                'city' => NULL,
                'state' => 'CA',
                'created' => '2017-03-07 16:56:46',
                'updated' => '2017-03-07 16:56:46',
            ],
            [
                'id' => '24',
                'username' => 'eduardo.martinez@aidshealth.org',
                'password' => '$2y$10$qqTmAMpXv4jhJdBefmpZV.gN6qOL4fHwYB4TNtjTYahVe4s8gSabq',
                'fullname' => 'Eduardo Martinez',
                'role' => 'mobilizer',
                'region_id' => '5',
                'city' => NULL,
                'state' => 'CA',
                'created' => '2017-03-07 16:57:12',
                'updated' => '2017-03-07 16:57:12',
            ],
            [
                'id' => '25',
                'username' => 'akil.patterson@aidshealth.org',
                'password' => '$2y$10$FOyjW2lmLfebKFzOegLd9OM6PjnPstAS.HJfHq9EvD/MPXExuyGw6',
                'fullname' => 'Akil Patterson',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Baltimore',
                'state' => 'MD',
                'created' => '2017-03-07 17:10:58',
                'updated' => '2017-03-07 17:10:58',
            ],
            [
                'id' => '26',
                'username' => 'will.booth@aidshealth.org',
                'password' => '$2y$10$Kc907Kmi4a2s5Rv7SHgpP.D6Put/n/eCGB9rKFt3azyGhUksvkZh6',
                'fullname' => 'Will Booth',
                'role' => 'mobilizer',
                'region_id' => '1',
                'city' => 'Dayton',
                'state' => 'OH',
                'created' => '2017-03-07 17:11:18',
                'updated' => '2017-03-07 17:11:18',
            ],
            [
                'id' => '27',
                'username' => 'elizabeth.mclendon@aidshe',
                'password' => '$2y$10$9CN5snoGcAd3YRgdQz3JH.Ogs296HOOFbZbfSwoKNHiz5F7z3xlRC',
                'fullname' => 'Elizabeth McLendon',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Columbia',
                'state' => 'SC',
                'created' => '2017-03-07 17:11:48',
                'updated' => '2017-03-07 17:11:48',
            ],
            [
                'id' => '28',
                'username' => 'veronica.brisco@aidshealth.org',
                'password' => '$2y$10$1xKQLBPi1CM7db46MGZCnOp7C0k6.BmlOyO.zqDXlCQxLVT0J7Qou',
                'fullname' => 'Veronica Brisco',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Lexington',
                'state' => 'SC',
                'created' => '2017-03-07 17:21:38',
                'updated' => '2017-03-07 17:21:38',
            ],
            [
                'id' => '29',
                'username' => 'rhiannon.marshall@aidshealth.org',
                'password' => '$2y$10$Z4PsEcIeVTQwT5t00QXvHuvO/IeYci4vzb.p3zGL.BM.fpg/eWWhm',
                'fullname' => 'Rhiannon Marshall',
                'role' => 'mobilizer',
                'region_id' => NULL,
                'city' => NULL,
                'state' => NULL,
                'created' => '2017-03-07 17:22:13',
                'updated' => '2017-03-07 17:22:13',
            ],
            [
                'id' => '30',
                'username' => 'raymond.thomas@aidshealth.org',
                'password' => '$2y$10$zD.fKGVGAXs4Up2x10Gn1egrydDHcmSC5i56Eae4H0MoxKhcEtw9S',
                'fullname' => 'Ray Thomas',
                'role' => 'mobilizer',
                'region_id' => '4',
                'city' => 'Washington',
                'state' => 'DC',
                'created' => '2017-03-07 17:22:47',
                'updated' => '2017-03-07 17:22:47',
            ],
            [
                'id' => '31',
                'username' => 'jonathan.jackson@aidshealth.org',
                'password' => '$2y$10$AO1M.ysmLiBK51xb4jd.F.ZfzlT0lCBvEAW/LJ2SJNiLMRotKr68S',
                'fullname' => 'Johnathan Jackson',
                'role' => 'mobilizer',
                'region_id' => NULL,
                'city' => NULL,
                'state' => NULL,
                'created' => '2017-03-07 17:23:14',
                'updated' => '2017-03-07 17:23:14',
            ],
        ];

        $table = $this->table('users');
        $table->insert($data)->save();
    }
}
